---

atom_upgrade_packages: false

atom_packages:
  - afterglow-monokai-syntax
  - atom-beautify
  - autoclose-html
  - autocomplete-plus
  - bottom-dock
  - double-tag
  - editorconfig
  - emmet
  - file-icons
  - git-plus
  - git-time-machine
  - grunt-manager
  - gulp-manager
  - highlight-line
  - highlight-selected
  - isotope-ui
  - language-ansible
  - language-docker
  - language-patch
  - linter
  - linter-manager
  - markdown-writer
  - open-terminal-here
  - php-twig
  - pigments
  - project-manager
  - sort-lines
  - svg-preview
  - todo-manager
  - travis-ci-status
  - tree-view-autoresize
